### ISSUE TITLE
Error in match.fun(FUN): 'ggfun("scales_transform_df")' is not a function, character or symbol

### ISSUE THREAD

**Issue by tungttnguyen** [tidyverse/ggplot2#5285]
I ran into a problem with `ggplotly()`. The following example worked with the CRAN version `3.4.2` but not with the dev version. Thanks!

``` r
library(dplyr)
library(ggplot2)
packageVersion("ggplot2")
#> [1] '3.4.2.9000'

data("airquality")

airquality <- airquality %>% 
  select(Month, Day, Temp) %>% 
  mutate(Date = as.Date(paste("1973", Month, Day, sep = "-")))

plt1 <- ggplot(airquality,
               aes(x = Date,
                   y = Temp)) +
  geom_line() +
  theme_bw()
plt1
```

![](https://i.imgur.com/W8zfKE4.png)

``` r

library(plotly)
packageVersion("plotly")
#> [1] '4.10.1'

ggplotly(plt1, 
         tooltip = c("x", "y", "color", "text"),
         dynamicTicks = TRUE) %>% 
  rangeslider() %>%
  layout(
    legend = list(orientation = "h", x = 0.1, y = -0.5)
  )
#> Error in match.fun(FUN): 'ggfun("scales_transform_df")' is not a function, character or symbol
```

<sup>Created on 2023-04-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by smouksassi** [comment]
please note that plotly has a different repo:
https://github.com/plotly/plotly.R/issues

**Comment by tungttnguyen** [comment]
> please note that plotly has a different repo: https://github.com/plotly/plotly.R/issues

The recent changes in `ggplot2` broke working codes. That's why I thought I should report it here

**Comment by tungttnguyen** [comment]
> This looks to me like a change in the internals have broken something in plotly.
> 
> If we look up the source of the `ggfun()` function that throws the error here:
> 
> https://github.com/plotly/plotly.R/blob/10e010088751efd5670d4daf2970b2eb5d91ea1a/R/ggplotly.R#L1393-L1395
> 
> We can see plotly uses the `getFromNamespace()` trick mentioned by Thomas at [this post](https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/#using-utilsgetfromnamespace). Admittedly, I have also used that trick, but the trick is very fragile because ggplot2 might change internals as they see fit.
> 
> In any case, it might make sense to loop in @cpsievert about this change sooner rather than later. I think the break stems from #5144, and it might make it easier to avoid `getFromNameSpace()` because the scales functions are now encapsulated in the `ScalesList` class that can be accessed at build time.

Thanks @teunbrand  for checking! I opened an issue on `plotly.R` to report it

**Comment by teunbrand** [comment]
Thanks for propagating the issue! I'll close this here then.

**Comment by fsalemi** [comment]
@tungttnguyen Hi there,
Were you able to resolve this issue? I am still getting this error:
`Error in match.fun(FUN) : 
  'ggfun("scales_transform_df")' is not a function, character or symbol`

Thanks

**Comment by cpsievert** [comment]
@fsalemi have you tried updating plotly?

**Comment by fsalemi** [comment]
@cpsievert Thank you for your response. I did upgrade plotly on my new computer last year. However, I was using my old laptop for a quick question yesterday, and I forgot the plotly version was still the old one.
Thanks again.
